name: publish
on: [push, pull_request]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ClaireAmor
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/claireamor/app-test-tech-lead:staging
        docker push ghcr.io/claireamor/app-test-tech-lead:staging
    - name: Coveralls
      uses: coverallsapp/github-action@v2
